//This file is generated by Dapper Code Generator
//Please do not write any code in this file. as it will be overwritten
using System;
using ReactBase.Data.Abstract;
namespace ReactBase.Data.TableModels{
public class Error : ModelBase {
public DateTime CreatedDateTime {get;set;}
public int Id {get;set;}
public int UserId {get;set;}
public string Message {get;set;}
public string Source {get;set;}
public string StackTrace {get;set;}
} // class Errors
}
