//This file is generated by Dapper Code Generator
//Please do not write any code in this file. as it will be overwritten
using System;
using ReactBase.Data.Abstract;
namespace ReactBase.Data.TableModels{
public class User : ModelBase {
public DateTime CreatedDateTime {get;set;}
public int Id {get;set;}
public string DisplayName {get;set;}
public string Email {get;set;}
public string Password {get;set;}
} // class Users
}
